//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.Composition;
using System.Data.Entity;
using Intellidesk.Data.Repositories.EF6.DataContext;
using Intellidesk.Data.Services;

namespace Intellidesk.Data.Models.DataContext
{
    [Export(typeof(IDataContextAsync))]
    public partial class AcadNetContext : Repositories.EF6.DataContext.DataContext
    {
        public AcadNetContext()
            : base(ConfigurationManager<AcadNetContext>.ConnectionString)
        {
        }

        private class Initializer : CreateDatabaseIfNotExists<AcadNetContext>
        {
            protected override void Seed(AcadNetContext context)
            {
                //IdentityRole role = context.Roles.Add(new IdentityRole("User"));

                //IdentityUser user = new IdentityUser("SampleUser");
                //user.Roles.Add(new IdentityUserRole { Role = role });
                //user.Claims.Add(new IdentityUserClaim
                //{
                //    ClaimType = "hasRegistered",
                //    ClaimValue = "true"
                //});

                //user.PasswordHash = new PasswordHasher().HashPassword("secret");
                //context.Users.Add(user);
                //context.SaveChanges();
                //base.Seed(context);
            }
        }


        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    }
}
