//-----------------
// <auto-generated>

namespace Intellidesk.Data.Models.DataContext
{
    public partial class MapInfoContext //: DataContext
    {
        //public MapInfoContext()
        //    //: base("name=MapInfoContext")
        //    : base(ConfigurationManager<MapInfoContext>.ConnectionString)
        //{
        //}

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    }
}
