//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.AcadNet.Data.Models.Intel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_BlockAttribute
    {
        public Nullable<decimal> BlockID { get; set; }
        public Nullable<decimal> BlockAttributeID { get; set; }
        public decimal LayoutID { get; set; }
        public decimal BlockIndex { get; set; }
        public decimal BlockAttributeIndex { get; set; }
        public string BlockAttributeName { get; set; }
        public string BlockAttributeValue { get; set; }
    
        public virtual LO_Block LO_Blocks { get; set; }
    }
}
