//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.AcadNet.Data.Models.Intel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_Block
    {
        public LO_Block()
        {
            this.LO_BlockAttributes = new HashSet<LO_BlockAttribute>();
            this.LO_Frames = new HashSet<LO_Frame>();
        }
    
        public Nullable<decimal> BlockID { get; set; }
        public decimal LayoutID { get; set; }
        public decimal BlockIndex { get; set; }
        public string BlockName { get; set; }
        public string BlockXrefName { get; set; }
        public string BlockHandle { get; set; }
    
        public virtual ICollection<LO_BlockAttribute> LO_BlockAttributes { get; set; }
        public virtual LO_Layout LO_Layouts { get; set; }
        public virtual ICollection<LO_Frame> LO_Frames { get; set; }
    }
}
