//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.AcadNet.Data.Models.Intel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_Frame
    {
        public Nullable<decimal> BlockID { get; set; }
        public Nullable<decimal> FrameID { get; set; }
        public decimal LayoutID { get; set; }
        public decimal BlockIndex { get; set; }
        public decimal FrameIndex { get; set; }
        public short FrameTypeID { get; set; }
        public double Xmin { get; set; }
        public double Ymin { get; set; }
        public double Xmax { get; set; }
        public double Ymax { get; set; }
    
        public virtual LO_Block LO_Blocks { get; set; }
    }
}
