//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.AcadNet.Data.Models.Intel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_Item
    {
        public Nullable<decimal> ItemID { get; set; }
        public string ItemName { get; set; }
        public decimal LayoutID { get; set; }
        public decimal ItemIndex { get; set; }
        public decimal ItemAttributeIndex { get; set; }
        public string ItemAttributeName { get; set; }
        public Nullable<decimal> ItemAttributeID { get; set; }
        public Nullable<decimal> BlockID { get; set; }
        public decimal BlockIndex { get; set; }
        public string BlockName { get; set; }
        public string XrefName { get; set; }
        public string LayerName { get; set; }
        public Nullable<double> Xpos { get; set; }
        public Nullable<double> Ypos { get; set; }
        public Nullable<double> Zpos { get; set; }
        public Nullable<double> Xscale { get; set; }
        public Nullable<double> Yscale { get; set; }
        public Nullable<double> Zscale { get; set; }
        public Nullable<double> Rotation { get; set; }
        public string ItemHandle { get; set; }
    }
}
