//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.AcadNet.Data.Models.Intel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_ItemAttribute
    {
        public Nullable<decimal> ItemID { get; set; }
        public Nullable<decimal> ItemAttributeID { get; set; }
        public decimal LayoutID { get; set; }
        public decimal ItemIndex { get; set; }
        public decimal ItemAttributeIndex { get; set; }
        public string ItemAttributeName { get; set; }
        public string ItemAttributeValue { get; set; }
    
        public virtual LO_Layout LO_Layouts { get; set; }
    }
}
