//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.AcadNet.Data.Models.Intel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_Layout
    {
        public LO_Layout()
        {
            this.LO_Bays = new HashSet<LO_Bay>();
            this.LO_Blocks = new HashSet<LO_Block>();
            this.LO_ItemAttributes = new HashSet<LO_ItemAttribute>();
        }
    
        public decimal LayoutID { get; set; }
        public string LayoutName { get; set; }
        public string LayoutType { get; set; }
        public string LayoutContents { get; set; }
        public string AccessType { get; set; }
        public string LayoutVersion { get; set; }
        public string Comment { get; set; }
        public string SiteName { get; set; }
        public string BuildingLevels { get; set; }
        public string ProcessName1 { get; set; }
        public string WSPW1 { get; set; }
        public string ProcessName2 { get; set; }
        public string WSPW2 { get; set; }
        public string ProcessName3 { get; set; }
        public string WSPW3 { get; set; }
        public string ProcessName4 { get; set; }
        public string WSPW4 { get; set; }
        public string CADFileName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<short> LayoutState { get; set; }
        public Nullable<bool> FSA { get; set; }
        public string ConfigSetName { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<LO_Bay> LO_Bays { get; set; }
        public virtual ICollection<LO_Block> LO_Blocks { get; set; }
        public virtual ICollection<LO_ItemAttribute> LO_ItemAttributes { get; set; }
    }
}
