//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadNet.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseNum
    {
        public int HouseNumberId { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Street { get; set; }
        public string HouseNumberName { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    }
}
