//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadNet.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zCityMapa
    {
        public zCityMapa()
        {
            this.zHouseNumberMapa = new HashSet<zHouseNumberMapa>();
            this.zStreetMapa = new HashSet<zStreetMapa>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    
        public virtual ICollection<zHouseNumberMapa> zHouseNumberMapa { get; set; }
        public virtual ICollection<zStreetMapa> zStreetMapa { get; set; }
    }
}
