//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadNet.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zStreetMapi
    {
        public zStreetMapi()
        {
            this.zHouseNumberMapi = new HashSet<zHouseNumberMapi>();
        }
    
        public int StreetId { get; set; }
        public int City { get; set; }
        public string StreetName { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    
        public virtual zCityMapi zCityMapi { get; set; }
        public virtual ICollection<zHouseNumberMapi> zHouseNumberMapi { get; set; }
    }
}
