//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.Data.Models.MapInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layers
    {
        public int LayerId { get; set; }
        public string LayerName { get; set; }
        public string DisplayNameHeb { get; set; }
        public Nullable<bool> BaseLayer { get; set; }
        public Nullable<double> Opacity { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
