//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.Data.Models.MapInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class zStreetMapa
    {
        public zStreetMapa()
        {
            this.zHouseNumberMapa = new HashSet<zHouseNumberMapa>();
        }
    
        public int StreetId { get; set; }
        public int City { get; set; }
        public string StreetName { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    
        public virtual zCityMapa zCityMapa { get; set; }
        public virtual ICollection<zHouseNumberMapa> zHouseNumberMapa { get; set; }
    }
}
