'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("d814ecd0-fb5e-4d7c-bc1a-173df02f6779")> 

'Original file name:
'Generation date: 05-Feb-12 02:20:40 AM
'''<summary>
'''There are no comments for MiDbSQLEntities in the schema.
'''</summary>
Partial Public Class MiDbSQLEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new MiDbSQLEntities object using the connection string found in the 'MiDbSQLEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=MiDbSQLEntities", "MiDbSQLEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new MiDbSQLEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MiDbSQLEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new MiDbSQLEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "MiDbSQLEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for Tikras in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property Tikras() As Global.System.Data.Objects.ObjectQuery(Of Tikra)
        Get
            If (Me._Tikras Is Nothing) Then
                Me._Tikras = MyBase.CreateQuery(Of Tikra)("[Tikras]")
            End If
            Return Me._Tikras
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Tikras As Global.System.Data.Objects.ObjectQuery(Of Tikra)
    '''<summary>
    '''There are no comments for Tikras in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToTikras(ByVal tikra As Tikra)
        MyBase.AddObject("Tikras", tikra)
    End Sub
End Class
'''<summary>
'''There are no comments for MiDbSQLModel.Tikra in the schema.
'''</summary>
'''<KeyProperties>
'''Level
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MiDbSQLModel", Name:="Tikra"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Tikra
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Tikra object.
    '''</summary>
    '''<param name="level">Initial value of Level.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateTikra(ByVal level As String) As Tikra
        Dim tikra As Tikra = New Tikra()
        tikra.Level = level
        Return tikra
    End Function
    '''<summary>
    '''There are no comments for property Division in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Division() As String
        Get
            Return Me._Division
        End Get
        Set
            Me.OnDivisionChanging(value)
            Me.ReportPropertyChanging("Division")
            Me._Division = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Division")
            Me.OnDivisionChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Division As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDivisionChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDivisionChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Level in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Level() As String
        Get
            Return Me._Level
        End Get
        Set
            Me.OnLevelChanging(value)
            Me.ReportPropertyChanging("Level")
            Me._Level = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Level")
            Me.OnLevelChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Level As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnLevelChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnLevelChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Eliv in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Eliv() As Global.System.Nullable(Of Single)
        Get
            Return Me._Eliv
        End Get
        Set
            Me.OnElivChanging(value)
            Me.ReportPropertyChanging("Eliv")
            Me._Eliv = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Eliv")
            Me.OnElivChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Eliv As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnElivChanging(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnElivChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Namedwg in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Namedwg() As String
        Get
            Return Me._Namedwg
        End Get
        Set
            Me.OnNamedwgChanging(value)
            Me.ReportPropertyChanging("Namedwg")
            Me._Namedwg = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Namedwg")
            Me.OnNamedwgChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Namedwg As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnNamedwgChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnNamedwgChanged()
        End Sub
    '''<summary>
    '''There are no comments for property typSlab in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property typSlab() As String
        Get
            Return Me._typSlab
        End Get
        Set
            Me.OntypSlabChanging(value)
            Me.ReportPropertyChanging("typSlab")
            Me._typSlab = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("typSlab")
            Me.OntypSlabChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _typSlab As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OntypSlabChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OntypSlabChanged()
        End Sub
    '''<summary>
    '''There are no comments for property proDatCons in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property proDatCons() As Global.System.Nullable(Of Date)
        Get
            Return Me._proDatCons
        End Get
        Set
            Me.OnproDatConsChanging(value)
            Me.ReportPropertyChanging("proDatCons")
            Me._proDatCons = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("proDatCons")
            Me.OnproDatConsChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _proDatCons As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproDatConsChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproDatConsChanged()
        End Sub
    '''<summary>
    '''There are no comments for property proDraw in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property proDraw() As Global.System.Nullable(Of Date)
        Get
            Return Me._proDraw
        End Get
        Set
            Me.OnproDrawChanging(value)
            Me.ReportPropertyChanging("proDraw")
            Me._proDraw = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("proDraw")
            Me.OnproDrawChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _proDraw As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproDrawChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproDrawChanged()
        End Sub
    '''<summary>
    '''There are no comments for property proFea in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property proFea() As Global.System.Nullable(Of Date)
        Get
            Return Me._proFea
        End Get
        Set
            Me.OnproFeaChanging(value)
            Me.ReportPropertyChanging("proFea")
            Me._proFea = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("proFea")
            Me.OnproFeaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _proFea As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproFeaChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproFeaChanged()
        End Sub
    '''<summary>
    '''There are no comments for property proConBeam in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property proConBeam() As Global.System.Nullable(Of Date)
        Get
            Return Me._proConBeam
        End Get
        Set
            Me.OnproConBeamChanging(value)
            Me.ReportPropertyChanging("proConBeam")
            Me._proConBeam = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("proConBeam")
            Me.OnproConBeamChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _proConBeam As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproConBeamChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproConBeamChanged()
        End Sub
    '''<summary>
    '''There are no comments for property proConPlate in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property proConPlate() As Global.System.Nullable(Of Date)
        Get
            Return Me._proConPlate
        End Get
        Set
            Me.OnproConPlateChanging(value)
            Me.ReportPropertyChanging("proConPlate")
            Me._proConPlate = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("proConPlate")
            Me.OnproConPlateChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _proConPlate As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproConPlateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnproConPlateChanged()
        End Sub
    '''<summary>
    '''There are no comments for property basePointX in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property basePointX() As Global.System.Nullable(Of Single)
        Get
            Return Me._basePointX
        End Get
        Set
            Me.OnbasePointXChanging(value)
            Me.ReportPropertyChanging("basePointX")
            Me._basePointX = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("basePointX")
            Me.OnbasePointXChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _basePointX As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnbasePointXChanging(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnbasePointXChanged()
        End Sub
    '''<summary>
    '''There are no comments for property BasePointY in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property BasePointY() As Global.System.Nullable(Of Single)
        Get
            Return Me._BasePointY
        End Get
        Set
            Me.OnBasePointYChanging(value)
            Me.ReportPropertyChanging("BasePointY")
            Me._BasePointY = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("BasePointY")
            Me.OnBasePointYChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _BasePointY As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnBasePointYChanging(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnBasePointYChanged()
        End Sub
    '''<summary>
    '''There are no comments for property DistancGr in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property DistancGr() As Global.System.Nullable(Of Single)
        Get
            Return Me._DistancGr
        End Get
        Set
            Me.OnDistancGrChanging(value)
            Me.ReportPropertyChanging("DistancGr")
            Me._DistancGr = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("DistancGr")
            Me.OnDistancGrChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _DistancGr As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDistancGrChanging(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDistancGrChanged()
        End Sub
    '''<summary>
    '''There are no comments for property flTsec in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property flTsec() As Global.System.Nullable(Of Short)
        Get
            Return Me._flTsec
        End Get
        Set
            Me.OnflTsecChanging(value)
            Me.ReportPropertyChanging("flTsec")
            Me._flTsec = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("flTsec")
            Me.OnflTsecChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _flTsec As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnflTsecChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnflTsecChanged()
        End Sub
    '''<summary>
    '''There are no comments for property kTors in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property kTors() As Global.System.Nullable(Of Single)
        Get
            Return Me._kTors
        End Get
        Set
            Me.OnkTorsChanging(value)
            Me.ReportPropertyChanging("kTors")
            Me._kTors = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("kTors")
            Me.OnkTorsChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _kTors As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnkTorsChanging(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnkTorsChanged()
        End Sub
    '''<summary>
    '''There are no comments for property nMeshX in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property nMeshX() As Global.System.Nullable(Of Short)
        Get
            Return Me._nMeshX
        End Get
        Set
            Me.OnnMeshXChanging(value)
            Me.ReportPropertyChanging("nMeshX")
            Me._nMeshX = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("nMeshX")
            Me.OnnMeshXChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _nMeshX As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnMeshXChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnMeshXChanged()
        End Sub
    '''<summary>
    '''There are no comments for property nMeshY in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property nMeshY() As Global.System.Nullable(Of Short)
        Get
            Return Me._nMeshY
        End Get
        Set
            Me.OnnMeshYChanging(value)
            Me.ReportPropertyChanging("nMeshY")
            Me._nMeshY = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("nMeshY")
            Me.OnnMeshYChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _nMeshY As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnMeshYChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnMeshYChanged()
        End Sub
    '''<summary>
    '''There are no comments for property par1 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par1() As Global.System.Nullable(Of Single)
        Get
            Return Me._par1
        End Get
        Set
            Me.Onpar1Changing(value)
            Me.ReportPropertyChanging("par1")
            Me._par1 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par1")
            Me.Onpar1Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par1 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar1Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar1Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par2 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par2() As Global.System.Nullable(Of Single)
        Get
            Return Me._par2
        End Get
        Set
            Me.Onpar2Changing(value)
            Me.ReportPropertyChanging("par2")
            Me._par2 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par2")
            Me.Onpar2Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par2 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar2Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar2Changed()
        End Sub
    '''<summary>
    '''There are no comments for property nCalc in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property nCalc() As Global.System.Nullable(Of Short)
        Get
            Return Me._nCalc
        End Get
        Set
            Me.OnnCalcChanging(value)
            Me.ReportPropertyChanging("nCalc")
            Me._nCalc = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("nCalc")
            Me.OnnCalcChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _nCalc As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnCalcChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnCalcChanged()
        End Sub
    '''<summary>
    '''There are no comments for property flChan in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property flChan() As Global.System.Nullable(Of Short)
        Get
            Return Me._flChan
        End Get
        Set
            Me.OnflChanChanging(value)
            Me.ReportPropertyChanging("flChan")
            Me._flChan = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("flChan")
            Me.OnflChanChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _flChan As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnflChanChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnflChanChanged()
        End Sub
    '''<summary>
    '''There are no comments for property num in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property num() As Global.System.Nullable(Of Short)
        Get
            Return Me._num
        End Get
        Set
            Me.OnnumChanging(value)
            Me.ReportPropertyChanging("num")
            Me._num = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("num")
            Me.OnnumChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _num As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnumChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnumChanged()
        End Sub
    '''<summary>
    '''There are no comments for property datold in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property datold() As Global.System.Nullable(Of Date)
        Get
            Return Me._datold
        End Get
        Set
            Me.OndatoldChanging(value)
            Me.ReportPropertyChanging("datold")
            Me._datold = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("datold")
            Me.OndatoldChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _datold As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OndatoldChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OndatoldChanged()
        End Sub
    '''<summary>
    '''There are no comments for property inBetonBem in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property inBetonBem() As Global.System.Nullable(Of Short)
        Get
            Return Me._inBetonBem
        End Get
        Set
            Me.OninBetonBemChanging(value)
            Me.ReportPropertyChanging("inBetonBem")
            Me._inBetonBem = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("inBetonBem")
            Me.OninBetonBemChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _inBetonBem As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonBemChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonBemChanged()
        End Sub
    '''<summary>
    '''There are no comments for property inBetonPlt in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property inBetonPlt() As Global.System.Nullable(Of Short)
        Get
            Return Me._inBetonPlt
        End Get
        Set
            Me.OninBetonPltChanging(value)
            Me.ReportPropertyChanging("inBetonPlt")
            Me._inBetonPlt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("inBetonPlt")
            Me.OninBetonPltChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _inBetonPlt As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonPltChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonPltChanged()
        End Sub
    '''<summary>
    '''There are no comments for property inBetonCol in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property inBetonCol() As Global.System.Nullable(Of Short)
        Get
            Return Me._inBetonCol
        End Get
        Set
            Me.OninBetonColChanging(value)
            Me.ReportPropertyChanging("inBetonCol")
            Me._inBetonCol = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("inBetonCol")
            Me.OninBetonColChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _inBetonCol As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonColChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonColChanged()
        End Sub
    '''<summary>
    '''There are no comments for property inBetonWal in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property inBetonWal() As Global.System.Nullable(Of Short)
        Get
            Return Me._inBetonWal
        End Get
        Set
            Me.OninBetonWalChanging(value)
            Me.ReportPropertyChanging("inBetonWal")
            Me._inBetonWal = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("inBetonWal")
            Me.OninBetonWalChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _inBetonWal As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonWalChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonWalChanged()
        End Sub
    '''<summary>
    '''There are no comments for property inBetonPil in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property inBetonPil() As Global.System.Nullable(Of Short)
        Get
            Return Me._inBetonPil
        End Get
        Set
            Me.OninBetonPilChanging(value)
            Me.ReportPropertyChanging("inBetonPil")
            Me._inBetonPil = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("inBetonPil")
            Me.OninBetonPilChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _inBetonPil As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonPilChanging(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OninBetonPilChanged()
        End Sub
    '''<summary>
    '''There are no comments for property ipar1 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar1() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar1
        End Get
        Set
            Me.Onipar1Changing(value)
            Me.ReportPropertyChanging("ipar1")
            Me._ipar1 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar1")
            Me.Onipar1Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar1 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar1Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar1Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar2 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar2() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar2
        End Get
        Set
            Me.Onipar2Changing(value)
            Me.ReportPropertyChanging("ipar2")
            Me._ipar2 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar2")
            Me.Onipar2Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar2 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar2Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar2Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar3 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar3() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar3
        End Get
        Set
            Me.Onipar3Changing(value)
            Me.ReportPropertyChanging("ipar3")
            Me._ipar3 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar3")
            Me.Onipar3Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar3 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar3Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar3Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar4 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar4() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar4
        End Get
        Set
            Me.Onipar4Changing(value)
            Me.ReportPropertyChanging("ipar4")
            Me._ipar4 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar4")
            Me.Onipar4Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar4 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar4Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar4Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar5 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar5() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar5
        End Get
        Set
            Me.Onipar5Changing(value)
            Me.ReportPropertyChanging("ipar5")
            Me._ipar5 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar5")
            Me.Onipar5Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar5 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar5Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar5Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar6 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar6() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar6
        End Get
        Set
            Me.Onipar6Changing(value)
            Me.ReportPropertyChanging("ipar6")
            Me._ipar6 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar6")
            Me.Onipar6Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar6 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar6Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar6Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar7 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar7() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar7
        End Get
        Set
            Me.Onipar7Changing(value)
            Me.ReportPropertyChanging("ipar7")
            Me._ipar7 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar7")
            Me.Onipar7Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar7 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar7Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar7Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar8 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar8() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar8
        End Get
        Set
            Me.Onipar8Changing(value)
            Me.ReportPropertyChanging("ipar8")
            Me._ipar8 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar8")
            Me.Onipar8Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar8 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar8Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar8Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar9 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar9() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar9
        End Get
        Set
            Me.Onipar9Changing(value)
            Me.ReportPropertyChanging("ipar9")
            Me._ipar9 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar9")
            Me.Onipar9Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar9 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar9Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar9Changed()
        End Sub
    '''<summary>
    '''There are no comments for property ipar10 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ipar10() As Global.System.Nullable(Of Short)
        Get
            Return Me._ipar10
        End Get
        Set
            Me.Onipar10Changing(value)
            Me.ReportPropertyChanging("ipar10")
            Me._ipar10 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ipar10")
            Me.Onipar10Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ipar10 As Global.System.Nullable(Of Short)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar10Changing(ByVal value As Global.System.Nullable(Of Short))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onipar10Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par3 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par3() As Global.System.Nullable(Of Single)
        Get
            Return Me._par3
        End Get
        Set
            Me.Onpar3Changing(value)
            Me.ReportPropertyChanging("par3")
            Me._par3 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par3")
            Me.Onpar3Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par3 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar3Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar3Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par4 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par4() As Global.System.Nullable(Of Single)
        Get
            Return Me._par4
        End Get
        Set
            Me.Onpar4Changing(value)
            Me.ReportPropertyChanging("par4")
            Me._par4 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par4")
            Me.Onpar4Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par4 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar4Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar4Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par5 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par5() As Global.System.Nullable(Of Single)
        Get
            Return Me._par5
        End Get
        Set
            Me.Onpar5Changing(value)
            Me.ReportPropertyChanging("par5")
            Me._par5 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par5")
            Me.Onpar5Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par5 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar5Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar5Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par6 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par6() As Global.System.Nullable(Of Single)
        Get
            Return Me._par6
        End Get
        Set
            Me.Onpar6Changing(value)
            Me.ReportPropertyChanging("par6")
            Me._par6 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par6")
            Me.Onpar6Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par6 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar6Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar6Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par7 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par7() As Global.System.Nullable(Of Single)
        Get
            Return Me._par7
        End Get
        Set
            Me.Onpar7Changing(value)
            Me.ReportPropertyChanging("par7")
            Me._par7 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par7")
            Me.Onpar7Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par7 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar7Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar7Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par8 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par8() As Global.System.Nullable(Of Single)
        Get
            Return Me._par8
        End Get
        Set
            Me.Onpar8Changing(value)
            Me.ReportPropertyChanging("par8")
            Me._par8 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par8")
            Me.Onpar8Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par8 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar8Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar8Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par9 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par9() As Global.System.Nullable(Of Single)
        Get
            Return Me._par9
        End Get
        Set
            Me.Onpar9Changing(value)
            Me.ReportPropertyChanging("par9")
            Me._par9 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par9")
            Me.Onpar9Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par9 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar9Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar9Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par10 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par10() As Global.System.Nullable(Of Single)
        Get
            Return Me._par10
        End Get
        Set
            Me.Onpar10Changing(value)
            Me.ReportPropertyChanging("par10")
            Me._par10 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par10")
            Me.Onpar10Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par10 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar10Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar10Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par11 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par11() As Global.System.Nullable(Of Single)
        Get
            Return Me._par11
        End Get
        Set
            Me.Onpar11Changing(value)
            Me.ReportPropertyChanging("par11")
            Me._par11 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par11")
            Me.Onpar11Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par11 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar11Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar11Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par12 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par12() As Global.System.Nullable(Of Single)
        Get
            Return Me._par12
        End Get
        Set
            Me.Onpar12Changing(value)
            Me.ReportPropertyChanging("par12")
            Me._par12 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par12")
            Me.Onpar12Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par12 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar12Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar12Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par13 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par13() As Global.System.Nullable(Of Single)
        Get
            Return Me._par13
        End Get
        Set
            Me.Onpar13Changing(value)
            Me.ReportPropertyChanging("par13")
            Me._par13 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par13")
            Me.Onpar13Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par13 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar13Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar13Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par14 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par14() As Global.System.Nullable(Of Single)
        Get
            Return Me._par14
        End Get
        Set
            Me.Onpar14Changing(value)
            Me.ReportPropertyChanging("par14")
            Me._par14 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par14")
            Me.Onpar14Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par14 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar14Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar14Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par15 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par15() As Global.System.Nullable(Of Single)
        Get
            Return Me._par15
        End Get
        Set
            Me.Onpar15Changing(value)
            Me.ReportPropertyChanging("par15")
            Me._par15 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par15")
            Me.Onpar15Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par15 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar15Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar15Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par16 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par16() As Global.System.Nullable(Of Single)
        Get
            Return Me._par16
        End Get
        Set
            Me.Onpar16Changing(value)
            Me.ReportPropertyChanging("par16")
            Me._par16 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par16")
            Me.Onpar16Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par16 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar16Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar16Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par17 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par17() As Global.System.Nullable(Of Single)
        Get
            Return Me._par17
        End Get
        Set
            Me.Onpar17Changing(value)
            Me.ReportPropertyChanging("par17")
            Me._par17 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par17")
            Me.Onpar17Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par17 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar17Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar17Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par18 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par18() As Global.System.Nullable(Of Single)
        Get
            Return Me._par18
        End Get
        Set
            Me.Onpar18Changing(value)
            Me.ReportPropertyChanging("par18")
            Me._par18 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par18")
            Me.Onpar18Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par18 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar18Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar18Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par19 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par19() As Global.System.Nullable(Of Single)
        Get
            Return Me._par19
        End Get
        Set
            Me.Onpar19Changing(value)
            Me.ReportPropertyChanging("par19")
            Me._par19 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par19")
            Me.Onpar19Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par19 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar19Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar19Changed()
        End Sub
    '''<summary>
    '''There are no comments for property par20 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property par20() As Global.System.Nullable(Of Single)
        Get
            Return Me._par20
        End Get
        Set
            Me.Onpar20Changing(value)
            Me.ReportPropertyChanging("par20")
            Me._par20 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("par20")
            Me.Onpar20Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _par20 As Global.System.Nullable(Of Single)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar20Changing(ByVal value As Global.System.Nullable(Of Single))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onpar20Changed()
        End Sub
End Class
