'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("cf469127-29ff-46b4-a006-25b78f734bc1")> 

'Original file name:
'Generation date: 31-Jan-12 00:59:20 AM
'''<summary>
'''There are no comments for Model1Container1 in the schema.
'''</summary>
Partial Public Class Model1Container1
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new Model1Container1 object using the connection string found in the 'Model1Container1' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=Model1Container1", "Model1Container1")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new Model1Container1 object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Model1Container1")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new Model1Container1 object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "Model1Container1")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
End Class
