//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ID.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResourcesEgHe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResourcesEgHe() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("General.Resources.GlobalResourcesEg", typeof(GlobalResourcesEgHe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעולות לביצוע.
        /// </summary>
        public static string ActionsToDo {
            get {
                return ResourceManager.GetString("ActionsToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל כלל יחידה.
        /// </summary>
        public static string AllUnit {
            get {
                return ResourceManager.GetString("AllUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חיל.
        /// </summary>
        public static string Army {
            get {
                return ResourceManager.GetString("Army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        public static string Canceling {
            get {
                return ResourceManager.GetString("Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר אחת מהאפשרויות.
        /// </summary>
        public static string ChooseOptions {
            get {
                return ResourceManager.GetString("ChooseOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדדי מפקד.
        /// </summary>
        public static string CommanderIndices {
            get {
                return ResourceManager.GetString("CommanderIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צור אירוע חדש.
        /// </summary>
        public static string CreateNewEvent {
            get {
                return ResourceManager.GetString("CreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דרגה.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך דרגה.
        /// </summary>
        public static string DegreeDate {
            get {
                return ResourceManager.GetString("DegreeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אירועים שנמחקו.
        /// </summary>
        public static string Deletedevents {
            get {
                return ResourceManager.GetString("Deletedevents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הינך רוצה לשכפל אירוע זה.
        /// </summary>
        public static string DoYouWantToDuplicateThisEvent {
            get {
                return ResourceManager.GetString("DoYouWantToDuplicateThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לצאת מהדף ללא שמירה.
        /// </summary>
        public static string DoYouWantToExitWithoutSaving {
            get {
                return ResourceManager.GetString("DoYouWantToExitWithoutSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך להעביר אירוע זה למאגר.
        /// </summary>
        public static string DoYouWantToMoveThisEventToArchive {
            get {
                return ResourceManager.GetString("DoYouWantToMoveThisEventToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שכפל.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שכפול.
        /// </summary>
        public static string duplicating {
            get {
                return ResourceManager.GetString("duplicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערוך.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך סיום.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך דרגה סיום.
        /// </summary>
        public static string EndDegreeDate {
            get {
                return ResourceManager.GetString("EndDegreeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך הצבה סיום.
        /// </summary>
        public static string EndPostingDate {
            get {
                return ResourceManager.GetString("EndPostingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפת הערכה.
        /// </summary>
        public static string EvaluationMap {
            get {
                return ResourceManager.GetString("EvaluationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפות שמסכמות לנו הערכות.
        /// </summary>
        public static string EvaluationMapText {
            get {
                return ResourceManager.GetString("EvaluationMapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל הערכה.
        /// </summary>
        public static string EvaluationModel {
            get {
                return ResourceManager.GetString("EvaluationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל זה מאפשר לנו לראות.
        /// </summary>
        public static string EvaluationModelText {
            get {
                return ResourceManager.GetString("EvaluationModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קשרי הערכה.
        /// </summary>
        public static string EvaluationRelations {
            get {
                return ResourceManager.GetString("EvaluationRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות אירוע.
        /// </summary>
        public static string EventDefinitions {
            get {
                return ResourceManager.GetString("EventDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחולל אירועים.
        /// </summary>
        public static string EventGenerator {
            get {
                return ResourceManager.GetString("EventGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; אירוע.
        /// </summary>
        public static string EventId {
            get {
                return ResourceManager.GetString("EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם אירוע.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת אירועים.
        /// </summary>
        public static string EventsList {
            get {
                return ResourceManager.GetString("EventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אחוז מילוי.
        /// </summary>
        public static string FillPercentage {
            get {
                return ResourceManager.GetString("FillPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות כלליות.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עבור.
        /// </summary>
        public static string GoOn {
            get {
                return ResourceManager.GetString("GoOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איתור מעריכים / מוערכים.
        /// </summary>
        public static string LocatingEvaluators {
            get {
                return ResourceManager.GetString("LocatingEvaluators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איתור של מועמדים לבקרה ובחירה מושכלת.
        /// </summary>
        public static string LocatingEvaluatorsText {
            get {
                return ResourceManager.GetString("LocatingEvaluatorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר למאגר.
        /// </summary>
        public static string MoveToArchive {
            get {
                return ResourceManager.GetString("MoveToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חובה לבחור אופציה אחת מתוך הרשימה.
        /// </summary>
        public static string MustChooseOneOptionFromList {
            get {
                return ResourceManager.GetString("MustChooseOneOptionFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערות.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גורם אחראי.
        /// </summary>
        public static string ResponsibleFactor {
            get {
                return ResourceManager.GetString("ResponsibleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירה.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסך נשמר בהצלחה.
        /// </summary>
        public static string ScreenSavedSuccessfully {
            get {
                return ResourceManager.GetString("ScreenSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש אירוע.
        /// </summary>
        public static string seachEvent {
            get {
                return ResourceManager.GetString("seachEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עונה.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לטובת בחירת היחידה נא סמן את היחידות  ולחץ על החץ.
        /// </summary>
        public static string SelectUnitInfo {
            get {
                return ResourceManager.GetString("SelectUnitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג שירות.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קביעת קשרים.
        /// </summary>
        public static string SetConnections {
            get {
                return ResourceManager.GetString("SetConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרת פוטנציאל.
        /// </summary>
        public static string SettingPotential {
            get {
                return ResourceManager.GetString("SettingPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל כוכב.
        /// </summary>
        public static string StarModel {
            get {
                return ResourceManager.GetString("StarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך התחלה.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך דרגה התחלה.
        /// </summary>
        public static string StartDegreeDate {
            get {
                return ResourceManager.GetString("StartDegreeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך הצבה התחלה.
        /// </summary>
        public static string StartPostingDate {
            get {
                return ResourceManager.GetString("StartPostingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטטוס.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל תת יחידה.
        /// </summary>
        public static string SubUnit {
            get {
                return ResourceManager.GetString("SubUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כלי.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חוקת כלי.
        /// </summary>
        public static string ToolConstitution {
            get {
                return ResourceManager.GetString("ToolConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מאפייני פוטנציאל.
        /// </summary>
        public static string ToolPotential {
            get {
                return ResourceManager.GetString("ToolPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מאפייני כלי.
        /// </summary>
        public static string ToolProperty {
            get {
                return ResourceManager.GetString("ToolProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידה מוערכת.
        /// </summary>
        public static string UnitEvaluated {
            get {
                return ResourceManager.GetString("UnitEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידה מעריכה.
        /// </summary>
        public static string UnitEvaluates {
            get {
                return ResourceManager.GetString("UnitEvaluates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הינך עומד למחוק את האירוע, כל הנתונים הקיימים יאבדו.
        /// </summary>
        public static string YouAreGoingToDeleteTheEvent {
            get {
                return ResourceManager.GetString("YouAreGoingToDeleteTheEvent", resourceCulture);
            }
        }
    }
}
