//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ID.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResourcesEg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResourcesEg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("General.Infrastructure.Resources.GlobalResourcesEg", typeof(GlobalResourcesEg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעולות לביצוע.
        /// </summary>
        public static string ActionsToDo {
            get {
                return ResourceManager.GetString("ActionsToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפעל.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפעלה.
        /// </summary>
        public static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אירועים פעילים.
        /// </summary>
        public static string ActiveEvents {
            get {
                return ResourceManager.GetString("ActiveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת מדדי מפקד לסוציומטרי יחידתי.
        /// </summary>
        public static string AddCommanderIndexText {
            get {
                return ResourceManager.GetString("AddCommanderIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לחץ כאן בשביל להוסיף טבלת קבוצות.
        /// </summary>
        public static string AddGroupTable {
            get {
                return ResourceManager.GetString("AddGroupTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת משתתף חדש.
        /// </summary>
        public static string AddNewParticipant {
            get {
                return ResourceManager.GetString("AddNewParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף משתתף.
        /// </summary>
        public static string AddParticipant {
            get {
                return ResourceManager.GetString("AddParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף שורה.
        /// </summary>
        public static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל כלל יחידה.
        /// </summary>
        public static string AllUnit {
            get {
                return ResourceManager.GetString("AllUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מערך.
        /// </summary>
        public static string Array {
            get {
                return ResourceManager.GetString("Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שבץ לקבוצה.
        /// </summary>
        public static string AssigningGroup {
            get {
                return ResourceManager.GetString("AssigningGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שבץ לתת יחידה.
        /// </summary>
        public static string AssigningSubUnit {
            get {
                return ResourceManager.GetString("AssigningSubUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        public static string Canceling {
            get {
                return ResourceManager.GetString("Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המועמד כבר קיים בפוטנציאל.
        /// </summary>
        public static string CandidateExistsInPotential {
            get {
                return ResourceManager.GetString("CandidateExistsInPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירות.
        /// </summary>
        public static string Choices {
            get {
                return ResourceManager.GetString("Choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר אחת מהאפשרויות.
        /// </summary>
        public static string ChooseOptions {
            get {
                return ResourceManager.GetString("ChooseOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סגירה.
        /// </summary>
        public static string Closure {
            get {
                return ResourceManager.GetString("Closure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדד המפקד.
        /// </summary>
        public static string CommanderIndex {
            get {
                return ResourceManager.GetString("CommanderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדד מפקד 1.
        /// </summary>
        public static string CommanderIndex1 {
            get {
                return ResourceManager.GetString("CommanderIndex1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדד מפקד 2.
        /// </summary>
        public static string CommanderIndex2 {
            get {
                return ResourceManager.GetString("CommanderIndex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדדי המפקד.
        /// </summary>
        public static string CommanderIndexes {
            get {
                return ResourceManager.GetString("CommanderIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל זה מאפשר לנו לראות.
        /// </summary>
        public static string CommanderIndexText {
            get {
                return ResourceManager.GetString("CommanderIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדדי מפקד.
        /// </summary>
        public static string CommanderIndices {
            get {
                return ResourceManager.GetString("CommanderIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אישור.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חיל.
        /// </summary>
        public static string Corp {
            get {
                return ResourceManager.GetString("Corp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צור אירוע חדש.
        /// </summary>
        public static string CreateNewEvent {
            get {
                return ResourceManager.GetString("CreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך הפצה.
        /// </summary>
        public static string DateDistribute {
            get {
                return ResourceManager.GetString("DateDistribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרת פוטנציאל.
        /// </summary>
        public static string DefiningPotential {
            get {
                return ResourceManager.GetString("DefiningPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק משתתף.
        /// </summary>
        public static string DeleteParticipant {
            get {
                return ResourceManager.GetString("DeleteParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג שאלון.
        /// </summary>
        public static string DisplayQuestionnaire {
            get {
                return ResourceManager.GetString("DisplayQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפות שמסכמות לנו הערכות.
        /// </summary>
        public static string DisplayQuestionnaireText {
            get {
                return ResourceManager.GetString("DisplayQuestionnaireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפץ שאלונים.
        /// </summary>
        public static string DistributeQuestionnaires {
            get {
                return ResourceManager.GetString("DistributeQuestionnaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך להפעיל את האירוע?.
        /// </summary>
        public static string DoYouWantToActivationEvent {
            get {
                return ResourceManager.GetString("DoYouWantToActivationEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הינך רוצה לשכפך אירוע זה ?.
        /// </summary>
        public static string DoYouWantToDuplicateThisEvent {
            get {
                return ResourceManager.GetString("DoYouWantToDuplicateThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לצאת מהדף ללא שמירה.
        /// </summary>
        public static string DoYouWantToExitWithoutSaving {
            get {
                return ResourceManager.GetString("DoYouWantToExitWithoutSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לסיים את האירוע?.
        /// </summary>
        public static string DoYouWantToFinishEvent {
            get {
                return ResourceManager.GetString("DoYouWantToFinishEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך להעביר אירוע זה למאגר ?.
        /// </summary>
        public static string DoYouWantToMoveThisEventToArchive {
            get {
                return ResourceManager.GetString("DoYouWantToMoveThisEventToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך לעצור את האירוע?.
        /// </summary>
        public static string DoYouWantToStopEvent {
            get {
                return ResourceManager.GetString("DoYouWantToStopEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שכפל.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשומה כפולה.
        /// </summary>
        public static string DuplicateItem {
            get {
                return ResourceManager.GetString("DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שכפול.
        /// </summary>
        public static string duplicating {
            get {
                return ResourceManager.GetString("duplicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערוך.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך סיום.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך הצבה סיום.
        /// </summary>
        public static string EndPostingDate {
            get {
                return ResourceManager.GetString("EndPostingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך דרגה סיום.
        /// </summary>
        public static string EndRankDate {
            get {
                return ResourceManager.GetString("EndRankDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מעריך.
        /// </summary>
        public static string Evaluate {
            get {
                return ResourceManager.GetString("Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוערך.
        /// </summary>
        public static string Evaluated {
            get {
                return ResourceManager.GetString("Evaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוערכים.
        /// </summary>
        public static string Evaluatedes {
            get {
                return ResourceManager.GetString("Evaluatedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפת הערכה.
        /// </summary>
        public static string EvaluationMap {
            get {
                return ResourceManager.GetString("EvaluationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפות שמסכמות לנו הערכות.
        /// </summary>
        public static string EvaluationMapText {
            get {
                return ResourceManager.GetString("EvaluationMapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל הערכה.
        /// </summary>
        public static string EvaluationModel {
            get {
                return ResourceManager.GetString("EvaluationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל זה מאפשר לנו לראות.
        /// </summary>
        public static string EvaluationModelText {
            get {
                return ResourceManager.GetString("EvaluationModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קשרי הערכה.
        /// </summary>
        public static string EvaluationRelations {
            get {
                return ResourceManager.GetString("EvaluationRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מעריכים.
        /// </summary>
        public static string Evaluators {
            get {
                return ResourceManager.GetString("Evaluators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות אירוע.
        /// </summary>
        public static string EventDefinitions {
            get {
                return ResourceManager.GetString("EventDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחולל אירועים.
        /// </summary>
        public static string EventGenerator {
            get {
                return ResourceManager.GetString("EventGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; אירוע.
        /// </summary>
        public static string EventId {
            get {
                return ResourceManager.GetString("EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם אירוע.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האירוע נשמר בצורה לא נכונה.
        /// </summary>
        public static string EventNotFullySaved {
            get {
                return ResourceManager.GetString("EventNotFullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת אירועים.
        /// </summary>
        public static string EventsList {
            get {
                return ResourceManager.GetString("EventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביצוע.
        /// </summary>
        public static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ייצא רשימה לאקסל.
        /// </summary>
        public static string ExportListToExcel {
            get {
                return ResourceManager.GetString("ExportListToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משפחה.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אחוז מילוי.
        /// </summary>
        public static string FillPercentage {
            get {
                return ResourceManager.GetString("FillPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיים אירוע.
        /// </summary>
        public static string FinishEvent {
            get {
                return ResourceManager.GetString("FinishEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם פרטי.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טופס.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות כלליות.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עבור.
        /// </summary>
        public static string GoOn {
            get {
                return ResourceManager.GetString("GoOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יבא.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טופס לאירוע בנוי בצורה לא נכונה.
        /// </summary>
        public static string ImproperlyConstructedEventForm {
            get {
                return ResourceManager.GetString("ImproperlyConstructedEventForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדד.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנחיות למילוי הטופס - נלקח מהטופס המקורי של אותו כלי הכולל את הסקלות של אותו טופס.
        /// </summary>
        public static string InstructionsToFillForm {
            get {
                return ResourceManager.GetString("InstructionsToFillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פתיח.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משפחה.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איתור מעריכים / מוערכים.
        /// </summary>
        public static string LocatingEvaluators {
            get {
                return ResourceManager.GetString("LocatingEvaluators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איתור של מועמדים לבקרה ובחירה מושכלת.
        /// </summary>
        public static string LocatingEvaluatorsText {
            get {
                return ResourceManager.GetString("LocatingEvaluatorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עומד בקריטריון.
        /// </summary>
        public static string MeetsCriterion {
            get {
                return ResourceManager.GetString("MeetsCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חסר חיבור שאלות בטופס לעץ נושאים.
        /// </summary>
        public static string MissingConnectQuestionToTreeSubject {
            get {
                return ResourceManager.GetString("MissingConnectQuestionToTreeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חסר מטא נתונים של יחידות או דרגות.
        /// </summary>
        public static string MissingMetaDataUnitsOrRanks {
            get {
                return ResourceManager.GetString("MissingMetaDataUnitsOrRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בהגדרת האירוע חסר מי מעריך את מי.
        /// </summary>
        public static string MissingWhoIsEvaluatingWho {
            get {
                return ResourceManager.GetString("MissingWhoIsEvaluatingWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר למאגר.
        /// </summary>
        public static string MoveToArchive {
            get {
                return ResourceManager.GetString("MoveToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר לביצוע.
        /// </summary>
        public static string MoveToExecution {
            get {
                return ResourceManager.GetString("MoveToExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הועבר למאגר.
        /// </summary>
        public static string MoveToRepository {
            get {
                return ResourceManager.GetString("MoveToRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos;.
        /// </summary>
        public static string Mum {
            get {
                return ResourceManager.GetString("Mum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חובה לבחור אופציה אח מתוך הרשימה.
        /// </summary>
        public static string MustChooseOneOptionFromList {
            get {
                return ResourceManager.GetString("MustChooseOneOptionFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש למלא שדה אחד לפחות במאפייני פוטנציאל.
        /// </summary>
        public static string MustFillOnePotential {
            get {
                return ResourceManager.GetString("MustFillOnePotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם קיים במערכת.
        /// </summary>
        public static string NameExist {
            get {
                return ResourceManager.GetString("NameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כינוי.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירה נכשלה.
        /// </summary>
        public static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos;.
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מ.א..
        /// </summary>
        public static string P_N_ {
            get {
                return ResourceManager.GetString("P.N.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתתפים.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השהה.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מושהה.
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; אישי.
        /// </summary>
        public static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מ.א. לא קיים.
        /// </summary>
        public static string PersonalNumberNotExist {
            get {
                return ResourceManager.GetString("PersonalNumberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טופס שאלון אישי.
        /// </summary>
        public static string PersonalQuestionnaireForm {
            get {
                return ResourceManager.GetString("PersonalQuestionnaireForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פוטנציאל משתתפים.
        /// </summary>
        public static string PotentialParticipants {
            get {
                return ResourceManager.GetString("PotentialParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכנה.
        /// </summary>
        public static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שאלון.
        /// </summary>
        public static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דרגה.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך דרגה.
        /// </summary>
        public static string RankDate {
            get {
                return ResourceManager.GetString("RankDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דרגות.
        /// </summary>
        public static string Ranks {
            get {
                return ResourceManager.GetString("Ranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רענן פוטנציאל.
        /// </summary>
        public static string RefreshPotential {
            get {
                return ResourceManager.GetString("RefreshPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערה.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערות.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיבת ההסרה.
        /// </summary>
        public static string RemoveReason {
            get {
                return ResourceManager.GetString("RemoveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גורם אחראי.
        /// </summary>
        public static string ResponsibleFactor {
            get {
                return ResourceManager.GetString("ResponsibleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפקיד.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמור.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירה.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המסך נשמר בהצלחה.
        /// </summary>
        public static string ScreenSavedSuccessfully {
            get {
                return ResourceManager.GetString("ScreenSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש אירוע.
        /// </summary>
        public static string seachEvent {
            get {
                return ResourceManager.GetString("seachEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עונה.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לטובת בחירת היחידה נא סמן את היחידות  ולחץ על החץ.
        /// </summary>
        public static string SelectUnitInfo {
            get {
                return ResourceManager.GetString("SelectUnitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג שירות.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קביעת קשרים.
        /// </summary>
        public static string SetConnections {
            get {
                return ResourceManager.GetString("SetConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרת פוטנציאל.
        /// </summary>
        public static string SettingPotential {
            get {
                return ResourceManager.GetString("SettingPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  מיוחדים.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל כוכב.
        /// </summary>
        public static string StarModel {
            get {
                return ResourceManager.GetString("StarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך התחלה.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך הצבה התחלה.
        /// </summary>
        public static string StartPostingDate {
            get {
                return ResourceManager.GetString("StartPostingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך דרגה התחלה.
        /// </summary>
        public static string StartRankDate {
            get {
                return ResourceManager.GetString("StartRankDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטטוס.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עצירה.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תת יחידה.
        /// </summary>
        public static string SubUnit {
            get {
                return ResourceManager.GetString("SubUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל תת יחידה.
        /// </summary>
        public static string SubUnitModel {
            get {
                return ResourceManager.GetString("SubUnitModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EG.
        /// </summary>
        public static string TMSClientName {
            get {
                return ResourceManager.GetString("TMSClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עצור.
        /// </summary>
        public static string To_Stop {
            get {
                return ResourceManager.GetString("To Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיים.
        /// </summary>
        public static string ToFinish {
            get {
                return ResourceManager.GetString("ToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כלי.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חוקת כלי.
        /// </summary>
        public static string ToolConstitution {
            get {
                return ResourceManager.GetString("ToolConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מאפייני פוטנציאל.
        /// </summary>
        public static string ToolPotential {
            get {
                return ResourceManager.GetString("ToolPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מאפייני כלי.
        /// </summary>
        public static string ToolProperty {
            get {
                return ResourceManager.GetString("ToolProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידה.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידה מוערכת.
        /// </summary>
        public static string UnitEvaluated {
            get {
                return ResourceManager.GetString("UnitEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידה מעריכה.
        /// </summary>
        public static string UnitEvaluates {
            get {
                return ResourceManager.GetString("UnitEvaluates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידות.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם ברצונך להעביר את האירוע לביצוע ?.
        /// </summary>
        public static string YouAreGoingMoveToExecution {
            get {
                return ResourceManager.GetString("YouAreGoingMoveToExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הינך עומד למחוק את האירוע, כל הנתונים הקיימים יאבדו.
        /// </summary>
        public static string YouAreGoingToDeleteTheEvent {
            get {
                return ResourceManager.GetString("YouAreGoingToDeleteTheEvent", resourceCulture);
            }
        }
    }
}
