//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ID.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResourcesEgEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResourcesEgEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("General.Resources.Resource1", typeof(GlobalResourcesEgEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionsToDo.
        /// </summary>
        public static string ActionsToDo {
            get {
                return ResourceManager.GetString("ActionsToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unit model.
        /// </summary>
        public static string AllUnit {
            get {
                return ResourceManager.GetString("AllUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Army.
        /// </summary>
        public static string Army {
            get {
                return ResourceManager.GetString("Army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling.
        /// </summary>
        public static string Canceling {
            get {
                return ResourceManager.GetString("Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one options.
        /// </summary>
        public static string ChooseOptions {
            get {
                return ResourceManager.GetString("ChooseOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander Indices.
        /// </summary>
        public static string CommanderIndices {
            get {
                return ResourceManager.GetString("CommanderIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Event.
        /// </summary>
        public static string CreateNewEvent {
            get {
                return ResourceManager.GetString("CreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Date.
        /// </summary>
        public static string DegreeDate {
            get {
                return ResourceManager.GetString("DegreeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted events.
        /// </summary>
        public static string Deletedevents {
            get {
                return ResourceManager.GetString("Deletedevents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Duplicate This Event.
        /// </summary>
        public static string DoYouWantToDuplicateThisEvent {
            get {
                return ResourceManager.GetString("DoYouWantToDuplicateThisEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Exit Without Saving.
        /// </summary>
        public static string DoYouWantToExitWithoutSaving {
            get {
                return ResourceManager.GetString("DoYouWantToExitWithoutSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoYouWantToMoveThisEventToArchive.
        /// </summary>
        public static string DoYouWantToMoveThisEventToArchive {
            get {
                return ResourceManager.GetString("DoYouWantToMoveThisEventToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicating.
        /// </summary>
        public static string duplicating {
            get {
                return ResourceManager.GetString("duplicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Degree Date.
        /// </summary>
        public static string EndDegreeDate {
            get {
                return ResourceManager.GetString("EndDegreeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End PostingDate.
        /// </summary>
        public static string EndPostingDate {
            get {
                return ResourceManager.GetString("EndPostingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Map.
        /// </summary>
        public static string EvaluationMap {
            get {
                return ResourceManager.GetString("EvaluationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Map Text.
        /// </summary>
        public static string EvaluationMapText {
            get {
                return ResourceManager.GetString("EvaluationMapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Model.
        /// </summary>
        public static string EvaluationModel {
            get {
                return ResourceManager.GetString("EvaluationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Mode lText.
        /// </summary>
        public static string EvaluationModelText {
            get {
                return ResourceManager.GetString("EvaluationModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Relations.
        /// </summary>
        public static string EvaluationRelations {
            get {
                return ResourceManager.GetString("EvaluationRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Definitions.
        /// </summary>
        public static string EventDefinitions {
            get {
                return ResourceManager.GetString("EventDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Generator.
        /// </summary>
        public static string EventGenerator {
            get {
                return ResourceManager.GetString("EventGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventId.
        /// </summary>
        public static string EventId {
            get {
                return ResourceManager.GetString("EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events List.
        /// </summary>
        public static string EventsList {
            get {
                return ResourceManager.GetString("EventsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillPercentage.
        /// </summary>
        public static string FillPercentage {
            get {
                return ResourceManager.GetString("FillPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go On.
        /// </summary>
        public static string GoOn {
            get {
                return ResourceManager.GetString("GoOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating Evaluators.
        /// </summary>
        public static string LocatingEvaluators {
            get {
                return ResourceManager.GetString("LocatingEvaluators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating Evaluators Text.
        /// </summary>
        public static string LocatingEvaluatorsText {
            get {
                return ResourceManager.GetString("LocatingEvaluatorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move To Archive.
        /// </summary>
        public static string MoveToArchive {
            get {
                return ResourceManager.GetString("MoveToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Choose One Option From List.
        /// </summary>
        public static string MustChooseOneOptionFromList {
            get {
                return ResourceManager.GetString("MustChooseOneOptionFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Factor.
        /// </summary>
        public static string ResponsibleFactor {
            get {
                return ResourceManager.GetString("ResponsibleFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Saved Successfully.
        /// </summary>
        public static string ScreenSavedSuccessfully {
            get {
                return ResourceManager.GetString("ScreenSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seach Event.
        /// </summary>
        public static string seachEvent {
            get {
                return ResourceManager.GetString("seachEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To select the unit, please select the units and click the arrow.
        /// </summary>
        public static string SelectUnitInfo {
            get {
                return ResourceManager.GetString("SelectUnitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        public static string ServiceType {
            get {
                return ResourceManager.GetString("ServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Connections.
        /// </summary>
        public static string SetConnections {
            get {
                return ResourceManager.GetString("SetConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Potential.
        /// </summary>
        public static string SettingPotential {
            get {
                return ResourceManager.GetString("SettingPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Model model.
        /// </summary>
        public static string StarModel {
            get {
                return ResourceManager.GetString("StarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Degree Date.
        /// </summary>
        public static string StartDegreeDate {
            get {
                return ResourceManager.GetString("StartDegreeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Posting Date.
        /// </summary>
        public static string StartPostingDate {
            get {
                return ResourceManager.GetString("StartPostingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Unit model.
        /// </summary>
        public static string SubUnit {
            get {
                return ResourceManager.GetString("SubUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Constitution.
        /// </summary>
        public static string ToolConstitution {
            get {
                return ResourceManager.GetString("ToolConstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Potential.
        /// </summary>
        public static string ToolPotential {
            get {
                return ResourceManager.GetString("ToolPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Property.
        /// </summary>
        public static string ToolProperty {
            get {
                return ResourceManager.GetString("ToolProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Evaluated.
        /// </summary>
        public static string UnitEvaluated {
            get {
                return ResourceManager.GetString("UnitEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Evaluates.
        /// </summary>
        public static string UnitEvaluates {
            get {
                return ResourceManager.GetString("UnitEvaluates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yo uAre Going To Delete The Event, all the existing data will get lost.
        /// </summary>
        public static string YouAreGoingToDeleteTheEvent {
            get {
                return ResourceManager.GetString("YouAreGoingToDeleteTheEvent", resourceCulture);
            }
        }
    }
}
