//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intellidesk.AcadNet.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://Vmmapinfo/AutocadMapviewerSvc/Acmv.svc?singleWsdl")]
        public string AutocadMapviewerUrl {
            get {
                return ((string)(this["AutocadMapviewerUrl"]));
            }
            set {
                this["AutocadMapviewerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06B75904-219F-4CA5-AC02-E3970A645F19")]
        public string PaletteSetId {
            get {
                return ((string)(this["PaletteSetId"]));
            }
            set {
                this["PaletteSetId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>C:\\Projects</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IncludeFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IncludeFolders"]));
            }
            set {
                this["IncludeFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int ProjectExplorerFoldersSectionHeight {
            get {
                return ((int)(this["ProjectExplorerFoldersSectionHeight"]));
            }
            set {
                this["ProjectExplorerFoldersSectionHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("380")]
        public int ProjectExplorerFilesSectionHeight {
            get {
                return ((int)(this["ProjectExplorerFilesSectionHeight"]));
            }
            set {
                this["ProjectExplorerFilesSectionHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://Vmmapinfo/AutocadMapviewerSvc/Acmv.svc/SetViewrXY/{0}/{1}")]
        public string MapinfoUrlFormat {
            get {
                return ((string)(this["MapinfoUrlFormat"]));
            }
            set {
                this["MapinfoUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intellidesk.AcadNet.Resources.Properties.Resources")]
        public string ResourceImages {
            get {
                return ((string)(this["ResourceImages"]));
            }
            set {
                this["ResourceImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://Vmmapinfo/AutocadMapviewerSvc/Acmv.svc?singleWsdl")]
        public string MapInfoApiViewerUrl {
            get {
                return ((string)(this["MapInfoApiViewerUrl"]));
            }
            set {
                this["MapInfoApiViewerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SearchText")]
        public string ToolPanelTop {
            get {
                return ((string)(this["ToolPanelTop"]));
            }
            set {
                this["ToolPanelTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string ToolPanelWidth {
            get {
                return ((string)(this["ToolPanelWidth"]));
            }
            set {
                this["ToolPanelWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:43210/")]
        public string IntelliDeskHost {
            get {
                return ((string)(this["IntelliDeskHost"]));
            }
            set {
                this["IntelliDeskHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://intellidesk/api/Draw/Point/?x=120&y=210")]
        public string IntelliDeskApiUrlSample {
            get {
                return ((string)(this["IntelliDeskApiUrlSample"]));
            }
            set {
                this["IntelliDeskApiUrlSample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ZoomDisplayFactor {
            get {
                return ((string)(this["ZoomDisplayFactor"]));
            }
            set {
                this["ZoomDisplayFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQL2008DB")]
        public string DbHost {
            get {
                return ((string)(this["DbHost"]));
            }
            set {
                this["DbHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vmmapinfo")]
        public string MapInfoApiHost {
            get {
                return ((string)(this["MapInfoApiHost"]));
            }
            set {
                this["MapInfoApiHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vmmapinfo/MapService/api/SetOnMap?x={0}&y={1}&user={2}")]
        public string MapInfoApiPointUrlFormat {
            get {
                return ((string)(this["MapInfoApiPointUrlFormat"]));
            }
            set {
                this["MapInfoApiPointUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intellidesk.AcadNet.Services.Properties.Resources")]
        public string ResourceClass {
            get {
                return ((string)(this["ResourceClass"]));
            }
            set {
                this["ResourceClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gis")]
        public string WorkLayerName {
            get {
                return ((string)(this["WorkLayerName"]));
            }
            set {
                this["WorkLayerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vmmapinfo/mapservice/api/setonmap/getgov?govname={0}&user={1}")]
        public string MapinfoApiFindUrlFormat {
            get {
                return ((string)(this["MapinfoApiFindUrlFormat"]));
            }
            set {
                this["MapinfoApiFindUrlFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string MapItHost {
            get {
                return ((string)(this["MapItHost"]));
            }
            set {
                this["MapItHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intellidesk")]
        public string ProjectName {
            get {
                return ((string)(this["ProjectName"]));
            }
            set {
                this["ProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Temp")]
        public string TempLayerName {
            get {
                return ((string)(this["TempLayerName"]));
            }
            set {
                this["TempLayerName"] = value;
            }
        }
    }
}
