//-----------------
// <auto-generated>
//-----------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;
using System.Xml.Serialization;
using Intellidesk.AcadNet.Data.Models.Entities;
using Intellidesk.AcadNet.Data.Repositories.EF6;
using Intellidesk.AcadNet.Data.Repositories.EF6;

namespace Intellidesk.AcadNet.Data.Models
{
    public class ConfigMetaData : BaseEntity
    {
        private string _configSetName;
        private string _paramName;
        private int? _int1;
        private string _str1;
        private string _str2;
        private string _longStr;

        private List<LayoutDictionary> _layoutOptions = new List<LayoutDictionary>();
        private LayoutDictionary _layerTypes;

        [Category("Generic")]
        [DisplayName("ConfigSet Name")]
        public string ConfigSetName
        {
            get { return _configSetName; }
            set
            {
                _configSetName = value;
                OnPropertyChanged();
            }
        }

        [Category("Generic")]
        [DisplayName("Int1")]
        public int? Int1
        {
            get { return _int1; }
            set
            {
                _int1 = value;
                OnPropertyChanged();
            }
        }

        [Category("Generic")]
        [DisplayName("Str1")]
        public string Str1
        {
            get { return _str1; }
            set
            {
                _str1 = value;
                OnPropertyChanged();
            }
        }

        [Category("Generic")]
        [DisplayName("Str2")]
        public string Str2
        {
            get { return _str2; }
            set
            {
                _str2 = value;
                OnPropertyChanged();
            }
        }

        [Category("Generic")]
        [DisplayName("LongStr")]
        public string LongStr
        {
            get { return _longStr; }
            set
            {
                _longStr = value;
                OnPropertyChanged();
            }
        }

        [Category("Generic")]
        [DisplayName("Layout Options")]
        public List<LayoutDictionary> LayoutOptions
        {
            get { return _layoutOptions; }
            set
            {
                _layoutOptions = value;
                OnPropertyChanged();
            }
        }
    }
}