//-----------------
// <auto-generated>
//-----------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using Intellidesk.AcadNet.Data.Models.Entities;
using Intellidesk.AcadNet.Data.Repositories.EF6;
using Intellidesk.AcadNet.Data.Repositories.EF6;

namespace Intellidesk.AcadNet.Data.Models
{
    public class RuleMetaData : BaseEntity
    {
        //IRule properties
        public string[] AttributePatternOn { get; set; }
        public string Comment { get; set; }

        [DefaultValue("")]
        public string DxfName { get; set; }
        public List<Tuple<string, int?, string>> ConfigDictionary { get; set; }

        [DefaultValue(null)]
        public string FilterBlockAttributesOn_Data { get; set; }
        public long Id { get; set; }

        //public int ID { get; set; }
        public bool isTypeFilterParent { get; set; }
        public bool IncludeNested { get; set; }
        //public bool IncludeTransform { get; set; }

        [DefaultValue(null)]
        public string LayoutCatalogSite_Data { get; set; }

        [DefaultValue(null)]
        public string LayoutCatalogOptions_Data { get; set; }
        public Point3D  MainPosition { get; set; }
        public string Name { get; set; }
        public int ColorIndex { get; set; }
        public string LayerDestination { get; set; }
        public short LayerTypeId { get; set; }
        public string LayerPatternOn_Data { get; set; }

        [DefaultValue(null)]
        public string LayerPatternOff_Data { get; set; }
        public string LineType { get; set; }
        public int LineTypeScale { get; set; }
        public long LineTypeId { get; set; }
        public string ObjectPattern { get; set; }
        public string ParameterList { get; set; }
        public long StartBlockIndex { get; set; }
        public string TooNameAttributes_Data { get; set; }
        public string TypeFilterOn_Data { get; set; }

        /// <summary> Reset indexes </summary>
        public static void RuleIndexesReset() { }
    }
}