//-----------------
// <auto-generated>
//-----------------

using System;
using Intellidesk.AcadNet.Data.Models.Entities;
using Intellidesk.AcadNet.Data.Repositories.EF6;
using Intellidesk.AcadNet.Data.Repositories.EF6;

namespace Intellidesk.AcadNet.Data.Models
{
    public class Settings : BaseEntity
    {
        public string UserName { get; set; }
        public string Data { get; set; }
        public DateTime? DateUpdated { get; set; }
        public DateTime? DateCreated { get; set; }
        public string Setting { get; set; }
    }
}