//-----------------
// <auto-generated>
//-----------------

using System.ComponentModel.DataAnnotations;
using Intellidesk.AcadNet.Data.Models.Entities;
using Intellidesk.AcadNet.Data.Repositories.EF6;
using Intellidesk.AcadNet.Data.Repositories.EF6;

namespace Intellidesk.AcadNet.Data.Models
{
    [MetadataType(typeof(StateMetaData))]
    public partial class State : BaseEntity
    {
    }

    public class StateMetaData : BaseEntity
    {
    }
}
